import {
  Checkroom,
  DeveloperMode,
  FaceRetouchingNatural,
  FitnessCenter,
  LiveTv,
  MusicNote,
  School,
  SportsEsports,
  TheaterComedy,
  Whatshot,
  TrendingUp,
  NewReleases,
  EmojiEvents,
  Movie,
  Headphones,
  MenuBook,
  Palette,
  Restaurant,
  Flight,
  Pets,
  Science,
  History,
} from "@mui/icons-material";
export const category = [
  { name: "New", icon: <NewReleases />, color: "#ff6b6b" },
  { name: "Trending", icon: <TrendingUp />, color: "#4ecdc4" },
  { name: "Music", icon: <MusicNote />, color: "#6c5ce7" },
  { name: "Movie", icon: <Movie />, color: "#a8e6cf" },
  { name: "Gaming", icon: <SportsEsports />, color: "#ffd93d" },
  { name: "Live", icon: <LiveTv />, color: "#ff8a5c" },
  { name: "Education", icon: <School />, color: "#3b9ae1" },
  { name: "Sport", icon: <FitnessCenter />, color: "#ff6b6b" },
  { name: "Comedy", icon: <TheaterComedy />, color: "#f9ca24" },
  { name: "Podcast", icon: <Headphones />, color: "#8e44ad" },
  { name: "Fashion", icon: <Checkroom />, color: "#e84393" },
  { name: "Crypto", icon: <DeveloperMode />, color: "#f39c12" },
  { name: "Beauty", icon: <FaceRetouchingNatural />, color: "#fd79a8" },
  { name: "Cooking", icon: <Restaurant />, color: "#e67e22" },
  { name: "Travel", icon: <Flight />, color: "#3498db" },
  { name: "Animals", icon: <Pets />, color: "#27ae60" },
  { name: "Science", icon: <Science />, color: "#2c3e50" },
  { name: "History", icon: <History />, color: "#7f8c8d" },
  { name: "Art", icon: <Palette />, color: "#e84393" },
  { name: "Books", icon: <MenuBook />, color: "#16a085" },
  { name: "Hot", icon: <Whatshot />, color: "#e74c3c" },
  { name: "Awards", icon: <EmojiEvents />, color: "#f1c40f" },
];
export const categoryColors = {
  New: "#ff6b6b",
  Trending: "#4ecdc4",
  Music: "#6c5ce7",
  Movie: "#a8e6cf",
  Gaming: "#ffd93d",
  Live: "#ff8a5c",
  Education: "#3b9ae1",
  Sport: "#ff6b6b",
  Comedy: "#f9ca24",
  Podcast: "#8e44ad",
  Fashion: "#e84393",
  Crypto: "#f39c12",
  Beauty: "#fd79a8",
  Cooking: "#e67e22",
  Travel: "#3498db",
  Animals: "#27ae60",
  Science: "#2c3e50",
  History: "#7f8c8d",
  Art: "#e84393",
  Books: "#16a085",
  Hot: "#e74c3c",
  Awards: "#f1c40f",
};
export const categoryGroups = {
  popular: ["New", "Trending", "Hot", "Awards"],
  entertainment: ["Music", "Movie", "Gaming", "Live", "Comedy"],
  lifestyle: ["Fashion", "Beauty", "Cooking", "Travel", "Animals"],
  education: ["Education", "Science", "History", "Books", "Art"],
  other: ["Podcast", "Sport", "Crypto"],
};
export default category;